#!/usr/bin/env bash

cd $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) || exit 1

cd /backend  # going to the main directory of the project

./manage.py makemessages --no-location -a -i translations_checking

locale=`find locale | grep "\.po"`
for l in $locale;
do
    sed -i '/^"POT-Creation-Date/d' $l
done
